import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Activity, ArrowUpRight, Bot, BrainCircuit, CircleDollarSign, Database, ExternalLink, Gauge, MessageSquare, Plus, RefreshCw, ShieldAlert, Sparkles, Tags, WalletCards, X } from "lucide-react";
import { client, type Briefing, type ChatMessage, type DecisionCenter, type Insight, type ModelPrice, type PriceChange, type Promotion, type Recommendation, type Source, type UserAsset, type ProviderRegistry } from "./api";

type View = "command" | "prices" | "changes" | "offers" | "assets";
const taskIcons: Record<string, string> = { coding: "</>", writing: "文", long_context: "长", reasoning: "∑", vision: "◉", daily_chat: "聊", local_offline: "⌂" };
const sourceName: Record<string, string> = { promotion: "官网", free_quota: "官网", pricing: "价格页面", provider_pricing: "价格页面", provider_api: "价格页面", github: "GitHub", community: "Linux.do", reddit: "Reddit" };
const money = (value: string | null, currency: string) => value === null ? "未公开" : `${Number(value).toFixed(3)} ${currency}/M`;
const timestamp = (value: string) => new Date(value).toLocaleString("zh-CN", { hour12: false });

export default function App() {
  const [view, setView] = useState<View>("command");
  const [decision, setDecision] = useState<DecisionCenter | null>(null); const [prices, setPrices] = useState<ModelPrice[]>([]);
  const [changes, setChanges] = useState<PriceChange[]>([]); const [promotions, setPromotions] = useState<Promotion[]>([]);
  const [sources, setSources] = useState<Source[]>([]); const [insights, setInsights] = useState<Insight[]>([]); const [assets, setAssets] = useState<UserAsset[]>([]);
  const [briefing, setBriefing] = useState<Briefing | null>(null); const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [registry, setRegistry] = useState<ProviderRegistry | null>(null);
  const [input, setInput] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const refresh = useCallback(async () => { try { setError(""); const [today, board, delta, promo, source, insight, asset, brief, discovered] = await Promise.all([client.decision(), client.prices(), client.changes(), client.promotions(), client.sources(), client.insights(), client.assets(), client.briefing(), client.registry()]); setDecision(today); setPrices(board.prices); setChanges(delta.changes); setPromotions(promo); setSources(source); setInsights(insight); setAssets(asset); setBriefing(brief); setRegistry(discovered); } catch (reason) { setError(reason instanceof Error ? reason.message : "无法读取本地 API Radar 服务"); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const run = async (kind: "scan" | "intelligence") => { try { if (kind === "scan") { const result = await client.scan(); setNotice(`已开始价格扫描：${result.providers.join("、")}`); } else { await client.intelligence(); setNotice("已开始采集官网与社区线索"); } window.setTimeout(() => void refresh(), 1800); } catch (reason) { setError(reason instanceof Error ? reason.message : "操作失败"); } };
  const send = async () => { const content = input.trim(); if (!content || busy) return; const next = [...messages, { role: "user" as const, content }]; setMessages(next); setInput(""); setBusy(true); try { const result = await client.chat(next); setMessages([...next, { role: "assistant", content: result.text }]); if (result.adjustment?.updated.length) { setNotice(`已根据对话调整偏好：${result.adjustment.updated.join("、")}`); void refresh(); } } catch (reason) { setError(reason instanceof Error ? reason.message : "助手暂时不可用"); } finally { setBusy(false); } };
  const navigation: [View, string, typeof Gauge][] = [["command", "决策中心", Gauge], ["prices", "价格行情", CircleDollarSign], ["changes", "模型变化", Activity], ["offers", "优惠与来源", Tags], ["assets", "我的资产", WalletCards]];
  return <div className="radar-shell"><aside><div className="brand"><span className="brand-orbit"><Bot size={20}/></span><span>API Radar</span></div><p className="side-caption">AI MODEL DECISION SYSTEM</p><nav>{navigation.map(([key, label, Icon]) => <button key={key} className={view === key ? "nav active" : "nav"} onClick={() => setView(key)}><Icon size={17}/>{label}</button>)}</nav><div className="side-status"><span></span>本地数据驾驶舱<br/><small>Key 不会保存到数据库</small></div></aside><main><header><div><p className="eyebrow">AI MODEL MARKET · DECISION FIRST</p><h1>{navigation.find(([key]) => key === view)?.[1]}</h1></div><div className="header-actions"><button className="button ghost" onClick={() => void refresh()} title="刷新"><RefreshCw size={16}/>刷新</button><button className="button" onClick={() => void run("scan")}><Activity size={16}/>扫描行情</button></div></header>{notice && <div className="notice">{notice}</div>}{error && <div className="error">{error}</div>}{view === "command" && <Command decision={decision} registry={registry} prices={prices} changes={changes} promotions={promotions} insights={insights} assets={assets} briefing={briefing} messages={messages} input={input} setInput={setInput} send={send} busy={busy}/>} {view === "prices" && <PriceBoard prices={prices}/>} {view === "changes" && <Changes changes={changes}/>} {view === "offers" && <Offers promotions={promotions} sources={sources} collect={() => void run("intelligence")}/>} {view === "assets" && <Assets assets={assets} refresh={refresh} announce={setNotice}/>}</main></div>;
}

function Command({ decision, registry, prices, changes, promotions, insights, assets, briefing, messages, input, setInput, send, busy }: { decision: DecisionCenter | null; registry: ProviderRegistry | null; prices: ModelPrice[]; changes: PriceChange[]; promotions: Promotion[]; insights: Insight[]; assets: UserAsset[]; briefing: Briefing | null; messages: ChatMessage[]; input: string; setInput: (value: string) => void; send: () => void; busy: boolean }) {
  const coding = decision?.recommendations.find((item) => item.task_id === "coding")?.recommendations ?? [];
  const lowPrice = useMemo(() => prices.filter((item) => item.input_price !== null && item.validation_status !== "invalid" && item.identity_status !== "unresolved").sort((a, b) => Number(a.input_price) - Number(b.input_price)).slice(0, 5), [prices]);
  return <><section className="hero"><div><p className="eyebrow">TODAY'S ACTION</p><h2>今天应该用哪个模型？</h2><ol>{decision?.actions.map((item) => <li key={item}>{item}</li>) ?? <li>正在读取价格与模型目录…</li>}</ol><p className="formula">{decision?.score_formula}</p></div><div className="hero-score"><span>AI VALUE</span><strong>{coding[0]?.value_score ?? "--"}</strong><small>编程首选</small></div></section><section className="metric-row"><Metric label="今日可选模型" value={String(prices.length)} detail="当前价格库"/><Metric label="已配置资产" value={String(assets.filter((item) => item.api_key_status === "active").length)} detail="优先推荐"/><Metric label="发现降价" value={String(changes.filter((item) => item.change_type === "decreased").length)} detail="相邻价格快照"/><Metric label="优惠活动" value={String(promotions.length)} detail="需核验条件"/></section><section className="section-heading"><div><p className="eyebrow">RECOMMENDATION CENTRE</p><h2>今日模型推荐</h2></div><span>TOP 5 · 按任务自动排序</span></section><div className="task-grid">{decision?.recommendations.map((task) => <TaskCard key={task.task_id} task={task.task} id={task.task_id} rows={task.recommendations}/>) ?? <LoadingCards/>}</div><section className="dashboard-grid"><div className="panel"><PanelTitle title="价格排行" label="LOWEST INPUT PRICE"/><div className="quote-list">{lowPrice.map((row) => <div className="quote" key={`${row.provider}/${row.model}`}><div><strong>{row.model}</strong><small>{row.provider} · {row.canonical_model_id ?? "待确认身份"}</small></div><b>{money(row.input_price, row.currency)}</b></div>)}</div></div><div className="panel"><PanelTitle title="模型变化" label="MARKET MOVES"/><Changes changes={changes.slice(0, 5)} compact/></div><div className="panel risk"><PanelTitle title="风险提醒" label="CHECK BEFORE BUY"/><ul><li>订阅套餐、交互式工具额度与普通 API 额度不能混用。</li><li>社区内容只作线索；价格和优惠以官网、价格页面为准。</li><li>评分是公开元数据与规则信号，不替代你的真实任务测试。</li></ul></div></section><IntelligencePanel insights={insights}/><Assistant briefing={briefing} messages={messages} input={input} setInput={setInput} send={send} busy={busy}/></>;
}

function TaskCard({ task, id, rows }: { task: string; id: string; rows: Recommendation[] }) { const lead = rows[0]; return <article className="task-card"><div className="task-title"><span>{taskIcons[id]}</span><div><h3>{task}</h3><p>{lead ? `首选：${lead.model}` : "等待价格数据"}</p></div>{lead && <b>{lead.value_score}</b>}</div>{lead ? <><div className="winner"><strong>🥇 {lead.model}</strong><span>{lead.provider}{lead.asset_available && " · 已有账号"}</span></div><div className="score-bars"><label>能力 <i style={{ width: `${lead.ability_score}%` }}/></label><label>速度 <i style={{ width: `${lead.speed_score}%` }}/></label></div><p className="reason">{lead.reason}</p><div className="alternatives">{rows.slice(1, 5).map((row, index) => <span key={`${row.provider_id}-${row.model}`}>{index + 2}. {row.model} <b>{row.value_score}</b></span>)}</div></> : <p className="reason">暂无可公开比较的价格。</p>}</article> }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function PanelTitle({ title, label }: { title: string; label: string }) { return <div className="panel-title"><div><p className="eyebrow">{label}</p><h2>{title}</h2></div></div>; }
function LoadingCards() { return <>{Array.from({ length: 7 }).map((_, index) => <div className="task-card skeleton" key={index}/>)}</>; }
function IntelligencePanel({ insights }: { insights: Insight[] }) { const label: Record<Insight["impact_level"], string> = { critical: "立即处理", high: "建议关注", medium: "需要确认", low: "无需行动" }; return <section className="panel intelligence-panel"><PanelTitle title="情报影响" label="SUMMARY · IMPACT · ACTION"/><p className="table-note">采集原文仅保存在后台证据库，首页只显示经过整理的摘要、影响和行动建议。</p>{insights.length ? insights.slice(0, 6).map((item) => <article className="insight" key={item.id}><span className={`impact ${item.impact_level}`}>{label[item.impact_level]}</span><div><strong>{item.title ?? "来源更新"}</strong><p>{item.summary}</p><small>{item.action} · {timestamp(item.captured_at)}</small></div></article>) : <p className="empty">暂未生成结构化情报摘要。</p>}</section>; }

function PriceBoard({ prices }: { prices: ModelPrice[] }) { const rows = useMemo(() => [...prices].sort((a, b) => Number(a.input_price ?? Infinity) - Number(b.input_price ?? Infinity)), [prices]); return <section className="panel table-panel"><PanelTitle title="模型价格库" label="MODEL_PRICE · CURRENT BOARD"/><p className="table-note">相同 Canonical ID 的模型可在不同平台横向比价；未确认身份的条目不会强行合并。</p><table><thead><tr><th>模型 / 平台</th><th>输入</th><th>输出</th><th>上下文</th><th>来源</th><th>更新时间</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.provider}/${row.model}`}><td><strong>{row.model}</strong><small>{row.provider} · {row.canonical_model_id ?? "身份待确认"}</small></td><td>{money(row.input_price, row.currency)}</td><td>{money(row.output_price, row.currency)}</td><td>{row.context_length ? `${(row.context_length / 1000).toFixed(0)}K` : "未公开"}</td><td>{row.source_url ? <a href={row.source_url} target="_blank">{sourceName[row.source_type] ?? "价格页面"} <ExternalLink size={12}/></a> : "-"}</td><td>{timestamp(row.updated_time)}</td></tr>)}</tbody></table></section>; }
function Changes({ changes, compact = false }: { changes: PriceChange[]; compact?: boolean }) { const content = changes.length ? changes.map((item) => <div className="change-row" key={`${item.provider_id}-${item.provider_model_id}`}><div><strong>{item.provider_model_name}</strong><small>{item.provider_name} · {money(item.input_price, item.currency)}</small></div><span className={`change ${item.change_type}`}>{item.change_type === "decreased" ? "降价" : item.change_type === "increased" ? "涨价" : item.change_type === "new" ? "新增" : "不变"}{item.input_price_delta && ` ${item.input_price_delta}`}</span></div>) : <p className="empty">暂无价格变化数据。</p>; return compact ? <div className="change-list">{content}</div> : <section className="panel"><PanelTitle title="模型价格变化" label="SNAPSHOT DELTAS"/><div className="change-list">{content}</div></section>; }
function Offers({ promotions, sources, collect }: { promotions: Promotion[]; sources: Source[]; collect: () => void }) { return <div className="two-column"><section className="panel"><div className="panel-title"><div><p className="eyebrow">VERIFIED / TO VERIFY</p><h2>优惠活动</h2></div><button className="button ghost" onClick={collect}><RefreshCw size={15}/>采集</button></div>{promotions.length ? promotions.map((item) => <article className="offer" key={item.id}><strong>{item.title}</strong><p>{item.description ?? "暂无公开详情"}</p><a href={item.source} target="_blank">查看来源 <ArrowUpRight size={13}/></a><small>采集于 {timestamp(item.captured_at)}</small></article>) : <p className="empty">暂无已确认优惠。</p>}</section><section className="panel"><PanelTitle title="情报来源" label="SOURCES & CAPTURE TIME"/><p className="table-note">官网和价格页面用于事实与评分；GitHub、Linux.do、Reddit 仅作为待核验线索。</p><div className="source-list">{sources.map((source) => <div className="source" key={source.url}><span className={source.fetch_success ? "source-dot success" : "source-dot failed"}/><div><strong>{source.title ?? source.url}</strong><small>{sourceName[source.source_type] ?? source.source_type} · {timestamp(source.captured_at)}</small></div><a href={source.url} target="_blank"><ExternalLink size={14}/></a></div>)}</div></section></div>; }
function Assets({ assets, refresh, announce }: { assets: UserAsset[]; refresh: () => Promise<void>; announce: (value: string) => void }) { const [provider, setProvider] = useState(""); const [status, setStatus] = useState<"active" | "inactive" | "unknown">("active"); const [plan, setPlan] = useState(""); const [models, setModels] = useState(""); const [saving, setSaving] = useState(false); const save = async (event: FormEvent) => { event.preventDefault(); if (!provider.trim()) return; setSaving(true); try { await client.saveAsset({ provider: provider.trim(), api_key_status: status, balance: null, currency: null, plan: plan.trim() || null, available_models: models.split(",").map((value) => value.trim()).filter(Boolean), enabled: true }); setProvider(""); setPlan(""); setModels(""); await refresh(); announce("资产已保存；推荐已优先考虑该平台。"); } finally { setSaving(false); } }; const remove = async (id: number) => { await client.deleteAsset(id); await refresh(); announce("资产记录已移除。"); }; return <div className="two-column"><section className="panel"><PanelTitle title="我的 API 资产" label="LOCAL ONLY · NO KEY STORED"/>{assets.length ? <div className="asset-list">{assets.map((asset) => <article className="asset" key={asset.id}><div><strong>{asset.provider}</strong><small>{asset.api_key_status === "active" ? "可用 Key 状态" : asset.api_key_status === "inactive" ? "暂不可用" : "尚未确认"}{asset.plan && ` · ${asset.plan}`}</small><p>{asset.available_models.length ? asset.available_models.join("、") : "未指定可用模型"}</p></div><button className="icon-danger" onClick={() => void remove(asset.id)} title="删除"><X size={16}/></button></article>)}</div> : <p className="empty">还没有资产。添加已有账号后，推荐会优先使用它。</p>}</section><section className="panel"><PanelTitle title="录入平台" label="ASSET PREFERENCE"/><form className="asset-form" onSubmit={(event) => void save(event)}><label>Provider<input value={provider} onChange={(event) => setProvider(event.target.value)} placeholder="例如 Packy、OpenRouter、SiliconFlow"/></label><label>API Key 状态<select value={status} onChange={(event) => setStatus(event.target.value as "active" | "inactive" | "unknown")}><option value="active">可用</option><option value="inactive">不可用</option><option value="unknown">未知</option></select></label><label>套餐（可选）<input value={plan} onChange={(event) => setPlan(event.target.value)} placeholder="例如 Claude Pro / 按量付费"/></label><label>可用模型（逗号分隔）<input value={models} onChange={(event) => setModels(event.target.value)} placeholder="Claude Sonnet, DeepSeek V3"/></label><button className="button" disabled={saving}><Plus size={16}/>{saving ? "保存中" : "保存资产"}</button></form><p className="privacy"><ShieldAlert size={15}/>只保存“状态、套餐、余额和可用模型”；绝不保存 API Key 明文。</p></section></div>; }
function Assistant({ briefing, messages, input, setInput, send, busy }: { briefing: Briefing | null; messages: ChatMessage[]; input: string; setInput: (value: string) => void; send: () => void; busy: boolean }) { return <section className="assistant panel"><div className="panel-title"><div><p className="eyebrow">DECISION COPILOT</p><h2>直接问 API Radar</h2></div><span className="assistant-badge"><BrainCircuit size={14}/>{briefing?.source === "llm" ? "本地模型增强" : "事实规则"}</span></div><p className="briefing">{briefing?.text ?? "正在生成今天的行动建议…"}</p><div className="chat-log">{messages.map((message, index) => <p className={`message ${message.role}`} key={index}>{message.content}</p>)}{busy && <p className="message assistant">正在根据当前资产、价格和任务要求整理…</p>}</div><form className="chat-form" onSubmit={(event) => { event.preventDefault(); void send(); }}><MessageSquare size={17}/><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="例如：我有 OpenRouter，今天要做中文代码审查，怎么选？"/><button className="button" disabled={!input.trim() || busy}><Sparkles size={15}/>询问</button></form></section>; }
